name: inputdemo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: this is input demo
        required: true
        default: dev
      tags:
        description: this is tag
        required: true
        default: 1.0.0
jobs:
 inputdemo:
   runs-on: ubuntu-latest
   steps:
     - name: run input demo
       run : echo "deploy the ${{inputs.tags}} application  ${{inputs.environment}}"
   
    
